// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DYi1WlYW6HZKr5fkSm-geG5zVSINdlY',
    appId: '1:230105299928:web:ad45965bd84b44c49b90ad',
    messagingSenderId: '230105299928',
    projectId: 'travel-app-c15b3',
    authDomain: 'travel-app-c15b3.firebaseapp.com',
    storageBucket: 'travel-app-c15b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_N4CMFs0cgN1KP3kqdnoRU5i0Tok_2g',
    appId: '1:230105299928:android:a444505c4fd7ef849b90ad',
    messagingSenderId: '230105299928',
    projectId: 'travel-app-c15b3',
    storageBucket: 'travel-app-c15b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9tsTtpWtnr-5qnNlxZ9QkHXmyY4YkEA',
    appId: '1:230105299928:ios:f1dfb1bcd0a5673d9b90ad',
    messagingSenderId: '230105299928',
    projectId: 'travel-app-c15b3',
    storageBucket: 'travel-app-c15b3.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9tsTtpWtnr-5qnNlxZ9QkHXmyY4YkEA',
    appId: '1:230105299928:ios:f1dfb1bcd0a5673d9b90ad',
    messagingSenderId: '230105299928',
    projectId: 'travel-app-c15b3',
    storageBucket: 'travel-app-c15b3.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DYi1WlYW6HZKr5fkSm-geG5zVSINdlY',
    appId: '1:230105299928:web:0379047699526df69b90ad',
    messagingSenderId: '230105299928',
    projectId: 'travel-app-c15b3',
    authDomain: 'travel-app-c15b3.firebaseapp.com',
    storageBucket: 'travel-app-c15b3.firebasestorage.app',
  );
}
