import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async';
import 'package:travel_app/auth_wrapper.dart';

// 1. IMPORT THE FILE GENERATED BY THE flutterfire configure COMMAND
import 'firebase_options.dart';

Future<void> addDummyTourists() async {
  final touristsCollection = FirebaseFirestore.instance.collection('tourists');

  final List<Map<String, dynamic>> dummyTourists = [
    {
      'name': 'Alice Paris',
      'email': 'alice.paris@example.com',
      'kyc_id': 'PARIS1234',
      'itinerary': 'Eiffel Tower -> Louvre Museum',
      'emergency_contact': '+33 123456789',
      'safety_score': 92.5,
      'is_tracking_active': true,
      'current_location': const GeoPoint(48.8566, 2.3522), // Paris
      'last_updated': Timestamp.now(),
      'status': 'normal',
    },
    {
      'name': 'Bob American',
      'email': 'bob.usa@example.com',
      'kyc_id': 'USA5678',
      'itinerary': 'New York -> Grand Canyon',
      'emergency_contact': '+1 987654321',
      'safety_score': 88.0,
      'is_tracking_active': true,
      'current_location': const GeoPoint(40.7128, -74.0060), // New York, USA
      'last_updated': Timestamp.now(),
      'status': 'distress', // simulate panic
    },
    {
      'name': 'Clara Ireland',
      'email': 'clara.ireland@example.com',
      'kyc_id': 'IRE7890',
      'itinerary': 'Dublin -> Cliffs of Moher',
      'emergency_contact': '+353 112233445',
      'safety_score': 96.0,
      'is_tracking_active': true,
      'current_location': const GeoPoint(53.3331, -6.2489), // Dublin, Ireland
      'last_updated': Timestamp.now(),
      'status': 'anomaly', // simulate AI anomaly
    },
    {
      'name': 'Dev Sharma',
      'email': 'dev.india@example.com',
      'kyc_id': 'IND4567',
      'itinerary': 'Delhi -> Agra (Taj Mahal)',
      'emergency_contact': '+91 9988776655',
      'safety_score': 90.0,
      'is_tracking_active': true,
      'current_location': const GeoPoint(28.6139, 77.2090), // New Delhi, India
      'last_updated': Timestamp.now(),
      'status': 'anomaly',
    },
  ];

  for (var tourist in dummyTourists) {
    // use email as ID to avoid duplicates
    await touristsCollection.doc(tourist['email']).set(tourist);
  }
}

// --- Main App Entry Point ---
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // 2. USE THE GENERATED FILE TO INITIALIZE FIREBASE
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await addDummyTourists();
  runApp(const TouristSafetyApp());
}

class TouristSafetyApp extends StatelessWidget {
  const TouristSafetyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Smart Tourist Safety',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.dark,
        ),
      ),
      home: AuthWrapper(),
    );
  }
}
